### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Benjozork** [Clashsoft/Angular-Gradle#1]
Hello,

I have noticed that your project is missing a license.

Lack of license on GitHub effectively means no explicit permission to reuse, modify or distribute this project - I am interested in this plugin for a project I will start soon, and a license would be required for me to be allowed to use it.

Here's a quick guide : https://choosealicense.com/

Thank you for your understanding,

**Comment by Clashsoft** [comment]
Hey, I just added the license in f3ee85e292c836280ba3410f15585a376884be31. It is included in the new release v0.1.7.

**Comment by Benjozork** [comment]
Thank you for the quick response :)
